name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests=2.24.0
  - pip=23.3.1
  - mlflow=2.3.1
  - hydra-core=1.3
  - pip:
      - wandb==0.15.12
      - hydra-joblib-launcher==1.1.2
